import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Dumbbell, 
  Brain, 
  BarChart3, 
  Calendar, 
  Target, 
  Zap, 
  ArrowRight, 
  CheckCircle2,
  Play,
  Star,
  Users,
  Trophy
} from "lucide-react";
import { useAuth } from "@/lib/auth";

export default function Landing() {
  const { isAuthenticated } = useAuth();

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Plans",
      description: "Get personalized workout plans generated by AI based on your goals, fitness level, and available equipment."
    },
    {
      icon: Dumbbell,
      title: "Exercise Library",
      description: "Access a comprehensive library of exercises with detailed instructions, videos, and muscle group targeting."
    },
    {
      icon: BarChart3,
      title: "Progress Tracking",
      description: "Monitor your fitness journey with detailed analytics, charts, and progress photos over time."
    },
    {
      icon: Calendar,
      title: "Smart Scheduling",
      description: "Plan your workouts with an intelligent calendar that adapts to your schedule and recovery needs."
    },
    {
      icon: Target,
      title: "Goal Setting",
      description: "Set and track fitness goals with milestone achievements and motivational progress indicators."
    },
    {
      icon: Zap,
      title: "Interactive Player",
      description: "Follow along with guided workout sessions featuring timers, set tracking, and rest periods."
    }
  ];

  const stats = [
    { value: "10K+", label: "Active Users" },
    { value: "500+", label: "Exercises" },
    { value: "50K+", label: "Workouts Completed" },
    { value: "4.9", label: "App Rating" }
  ];

  const testimonials = [
    {
      name: "Sarah M.",
      role: "Fitness Enthusiast",
      content: "FitStack transformed my workout routine. The AI plans are incredibly smart and adapt to my progress.",
      rating: 5
    },
    {
      name: "Mike T.",
      role: "Personal Trainer",
      content: "I recommend FitStack to all my clients. It's like having a digital training partner.",
      rating: 5
    },
    {
      name: "Emily R.",
      role: "Beginner",
      content: "As someone new to fitness, the guided workouts and exercise library made starting so much easier.",
      rating: 5
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <header className="fixed top-0 left-0 right-0 z-50 glass border-b border-border">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between gap-4">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer" data-testid="link-home">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <Dumbbell className="w-5 h-5 text-primary-foreground" />
              </div>
              <span className="font-bold text-xl">FitStack</span>
            </div>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <a href="#features" className="text-muted-foreground hover:text-foreground transition-colors" data-testid="link-features">Features</a>
            <a href="#testimonials" className="text-muted-foreground hover:text-foreground transition-colors" data-testid="link-testimonials">Testimonials</a>
            <a href="#pricing" className="text-muted-foreground hover:text-foreground transition-colors" data-testid="link-pricing">Pricing</a>
          </nav>
          <div className="flex items-center gap-3">
            {isAuthenticated ? (
              <Link href="/dashboard">
                <Button data-testid="button-dashboard">Go to Dashboard</Button>
              </Link>
            ) : (
              <>
                <Link href="/login">
                  <Button variant="ghost" data-testid="button-login">Log in</Button>
                </Link>
                <Link href="/signup">
                  <Button data-testid="button-signup">Get Started</Button>
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-chart-2/5" />
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-chart-2/10 rounded-full blur-3xl" />
        
        <div className="relative max-w-7xl mx-auto px-6">
          <div className="text-center max-w-4xl mx-auto">
            <Badge variant="secondary" className="mb-6">
              <Zap className="w-3 h-3 mr-1" />
              AI-Powered Fitness
            </Badge>
            <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6">
              Your Personal
              <span className="gradient-text"> AI Fitness</span>
              <br />Assistant
            </h1>
            <p className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-2xl mx-auto">
              Transform your fitness journey with personalized AI workout plans, progress tracking, and an interactive exercise library.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link href="/signup">
                <Button size="lg" className="text-lg px-8 py-6" data-testid="button-hero-signup">
                  Start Free Trial
                  <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              </Link>
              <Button size="lg" variant="outline" className="text-lg px-8 py-6" data-testid="button-watch-demo">
                <Play className="w-5 h-5 mr-2" />
                Watch Demo
              </Button>
            </div>
          </div>

          {/* Stats */}
          <div className="mt-20 grid grid-cols-2 md:grid-cols-4 gap-6">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <div className="text-4xl md:text-5xl font-bold gradient-text mb-2">{stat.value}</div>
                <div className="text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 md:py-32 bg-muted/30">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">Features</Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Everything You Need to Succeed</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              FitStack provides all the tools you need to build your ideal workout routine and track your progress.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature) => (
              <Card key={feature.title} className="hover-elevate cursor-default">
                <CardContent className="p-6">
                  <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4">
                    <feature.icon className="w-6 h-6 text-primary" />
                  </div>
                  <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 md:py-32">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">How It Works</Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Get Started in 3 Simple Steps</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "01", title: "Create Your Profile", description: "Tell us about your fitness goals, experience level, and available equipment." },
              { step: "02", title: "Get Your AI Plan", description: "Our AI generates a personalized workout plan tailored to your needs." },
              { step: "03", title: "Start Training", description: "Follow guided workouts, track your progress, and crush your goals." }
            ].map((item, index) => (
              <div key={item.step} className="relative">
                <div className="text-8xl font-bold text-muted/50 absolute -top-6 left-0">{item.step}</div>
                <div className="relative pt-12">
                  <h3 className="text-2xl font-semibold mb-3">{item.title}</h3>
                  <p className="text-muted-foreground">{item.description}</p>
                </div>
                {index < 2 && (
                  <div className="hidden md:block absolute top-16 right-0 w-16 h-0.5 bg-border translate-x-1/2" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-20 md:py-32 bg-muted/30">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">Testimonials</Badge>
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Loved by Fitness Enthusiasts</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((testimonial) => (
              <Card key={testimonial.name}>
                <CardContent className="p-6">
                  <div className="flex gap-1 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="w-5 h-5 fill-chart-4 text-chart-4" />
                    ))}
                  </div>
                  <p className="text-lg mb-4">"{testimonial.content}"</p>
                  <div>
                    <div className="font-semibold">{testimonial.name}</div>
                    <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 md:py-32">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <div className="bg-gradient-to-br from-primary to-chart-2 rounded-3xl p-12 md:p-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Ready to Transform Your Fitness?
            </h2>
            <p className="text-xl text-white/80 mb-8">
              Join thousands of users who have already started their fitness journey with FitStack.
            </p>
            <Link href="/signup">
              <Button size="lg" variant="secondary" className="text-lg px-8 py-6" data-testid="button-cta-signup">
                Get Started Free
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-border">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <Dumbbell className="w-5 h-5 text-primary-foreground" />
              </div>
              <span className="font-bold text-xl">FitStack</span>
            </div>
            <p className="text-muted-foreground text-sm">
              © 2024 FitStack. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
